### ISSUE TITLE
Convert this repository into a cookie cutter template such that it can be used to update the other repos

### ISSUE THREAD

**Issue by ehsteve** [HERMES-SOC/hermes_instrument#19]
To make it easier to make updates to the template and propagate them to the instrument team repositories, it would be much easier if this were a [cookiecutter](https://www.cookiecutter.io) template. This template can then be "re-applied" to the repository to bring updates easily and quickly. Otherwise this has to be done by hand.

**Comment by dbarrous** [comment]
Cleaning out issue since it has been done with the Cruft implementation
