### ISSUE TITLE
VSCode linting configuration needs to be udpated

### ISSUE THREAD

**Issue by ehsteve** [HERMES-SOC/hermes_instrument#33]
All uses of the `python.linting` configuration namespace is now deprecated by Visual Studio code. See this [article](https://github.com/microsoft/vscode-python/wiki/Migration-to-Python-Tools-Extensions). Python linting tools have been moved to extensions.

This update needs to be made to all of the instrument packages.

**Comment by dbarrous** [comment]
Have fixed this in:
https://github.com/HERMES-SOC/hermes_spani/pull/24
https://github.com/HERMES-SOC/hermes_nemisis/pull/21
https://github.com/HERMES-SOC/hermes_merit/pull/19
https://github.com/HERMES-SOC/hermes_eea/pull/32
